name: HHSD AUP Automation
on:
  push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Dependencies
        run: sudo apt install -y httrack webhttrack wget
